`PyList::new` and `PyTuple::new` are now fallible due to `IntoPyObject` migration.