Make `PyErr` internals thread-safe.
